# Generated by Django 3.0.4 on 2020-09-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('telephone', models.CharField(max_length=15, verbose_name='Telephone')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Человек',
                'verbose_name_plural': 'Люди',
            },
        ),
    ]
