# Generated by Django 3.0.4 on 2020-10-03 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='MyUser',
        ),
    ]
