# Generated by Django 3.0.4 on 2020-10-03 13:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_auto_20201003_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=60, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=60, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=60, verbose_name='Отчество')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Номер телефона')),
                ('links', models.CharField(blank=True, max_length=255, verbose_name='Ссылки')),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name="JSON'ы")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='testapp.MyUser')),
            ],
        ),
    ]
