# Generated by Django 3.0.4 on 2020-10-05 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_auto_20201004_1230'),
    ]

    operations = [
        migrations.DeleteModel(
            name='People',
        ),
    ]
